### ISSUE TITLE
Rename the app.

### ISSUE THREAD

**Issue by kordless** [x74353/SaveAmphetamine#6]
That's the whole ticket.

**Comment by clonardo** [comment]
Screw that. Apple’s approach here is autocratic, arbitrary, and generally ridiculous.

**Comment by lzilioli** [comment]
Personally I had only vaguely heard the term amphetamine before this app came along. When caffeine stopped working and I downloaded this app to my MacBook back in the day, I definitely had to Google what amphetamines were so that I could understand the metaphor and how it fit the theme from caffeine. 

 I definitely wondered why the escalation from coffee to pills when I downloaded.

I think you should ask yourself if this app needs to be the thing introducing people to the concept of amphetamines or should they stumble on them themselves?

The comparison to GTA is disingenuous at best. No specific drug is mentioned in the GTA App Store listing. As a parent I can keep my kids from being exposed to the concepts contained INSIDE of the GTA app better than I can from being exposed to the concept of amphetamine. You can't censor App Store listings from children the way you can censor apps themselves.

**Comment by x74353** [comment]
@lzilioli Thanks for your feedback. I can understand where you are coming from. For each of us, it’s going to be different things that we feel uncomfortable with. For me, with my children (8yo, 10yo) we have honest and frank discussion about real life issues such as addiction and drug use. My children understand that my app Amphetamine is not an endorsement or promotion of substance abuse.

GTA may not be the best comparison as its app name and icon don’t run afoul of the guidelines, but there are a lot of other apps that feature a marijuana leaf in their icon and similar. Thanks again. ❤️

**Comment by lzilioli** [comment]
@x74353 totally appreciate your response as well. I 100% agree that a mature child would be able to handle an app named amphetamine without it leading to issues down the road. I can also appreciate Apple's position that not everybody is going to be so mature.

I would also caution against falsely equivocating weed with amphetamines. Weed is a naturally occurring plant one could grow in their backyard—the harms of weed, in the worst case, are far less severe than the harms of amphetamines in the worst cases.  

Appreciate the discussion either way. I do feel for you being faced with potentially having to rebrand the app. You'll have my support either way it goes. I recommend it to everyone I know.

**Comment by x74353** [comment]
@lzilioli I live in a US state where recreational marijuana is fully legalized for adult use, so I understand where you are coming from about not comparing the two. The point I was trying to make is that marijuana remains an illegal drug/controlled substance (however you want to define it) at the federal level in the US, and in other countries it is not legalized at all.

The same could be said for the Coca leaf, which, while naturally occurring, is listed on the United Nations Convention on Narcotic Drugs as a Schedule 1 substance, making its use illegal.
